#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a gimp desktop='^8' follow=on
#bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a qimgv desktop='^10' follow=on
bspc rule -a Thonny follow=on layer=normal

#AutoStart
picom &

#.$HOME/Downloads/repos/eww/target/release/eww open bar &

~/.config/polybar/launch.sh &

feh --bg-fill ~/.dotfiles/themes/Minimalist/Wallpapers/girl.png &

picom --experimental-backends &

#eww open bar

